version: '3.1'
services:
    nginx:
        hostname: localhost
        image: umkus/nginx-boilerplate
        ports:
            - 80:80
            - 443:443
        secrets:
            - cert.crt
            - cert.key
    fpm:
        image: umkus/nginx-boilerplate-php

secrets:
    cert.crt:
        external: true
    cert.key:
        external: true
