nginx:
  container_name: example.com
  image: nginx
  ports:
    - 80:80
    - 443:443
  volumes:
    - ./test/www/:/var/www/example.com/:ro
    - ./src/:/etc/nginx/
  links:
    - php

php:
  container_name: php.example.com
  image: php:fpm
  expose:
    - 9000
  volumes:
    - ./test/www/:/var/www/example.com/:ro
