version: '3.1'
services:
    nginx:
        container_name: nginx
        restart: always
        build: .
        volumes:
            - ./logs/:/var/log/nginx/
            - ./:/etc/nginx/:ro

    fpm:
        container_name: fpm
        restart: always
